package:
  name: gbs
  version:  0.1.8

source:  
  # git_url: https://github.com/ssg-aero/gbs.git
  path: ../

build:
requirements:
  build:
    - {{ compiler('cxx') }}
    - vs2019_win-64 [win]
    - ninja
    - cmake 
    # - libiges # for copy
    # - tbb <2021.0
  host:
    # - vs2019_win-64
    - python=3.9
    - python-devtools
    - pybind11
    # - occt >=7.4
    - nlopt
    - vtk >=9.0
    - eigen
    - boost >=1.74
    # - gtest
    # - sundials 
    # - sphinx
    # - sphinx-rtd-theme
    # - breathe
    # - doxygen
    - rapidjson
    - fmt
    - libiges
    - tbb <2021.0 [linux] # upgrade asap when other package will be ready
  run:
    - python=3.9
    - pytest
    - boost >=1.74
    - nlopt
    - vtk >=9.0
    # - eigen
    - rapidjson
    - fmt
    - libiges
    - jupyterlab
    - pythreejs
    - pyvista
    # - occt >=7.4
    - tbb <2021.0 [linux] # upgrade asap when other package will be ready
about:
  home: http://www.ssg-aero.com
  license: LGPL3
test:
  imports:
    - pygbs.gbs
